### ISSUE TITLE
[Xenial] Clock always crashes

### ISSUE THREAD

**Issue by Flohack74** [ubports/clock-app#75] opened 2018-05-24 17:47 UTC
_From @jonnius on May 24, 2018 10:58_

- Device: FP2
- Channel: 16.04/devel
- Build: r304

### Steps to reproduce
Open clock core app.

### Expected behavior
It does not crash.

### Actual behavior
It crashes after a few seconds. I can't disable my daily alarm :(

### Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubuntu-touch/files/2034954/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubuntu-touch/files/2034955/UTlogcat.txt)
[Clock Log](https://paste.ubuntu.com/p/kfhQGHTFQn/)

_Copied from original issue: ubports/ubuntu-touch#630_

**Comment by Flohack74** [comment] 2018-05-24 17:48
You probably have the 15.04 version in use. The vanilla 16.04 version works, but I dont know without wiping the phone how you could get the right version?

**Comment by dark-eye** [comment] 2018-05-25 22:47
I think this is a duplicate of #70.

**Comment by zubozrout** [comment] 2018-05-26 21:48
I've cleared all clock app files I know of (cache, config, local/share) and yet the app crashes for me on Xenial. Attaching the log: [clock-app.log](https://github.com/ubports/clock-app/files/2041978/clock-app.log)

**Comment by advocatux** [comment] 2018-05-27 10:07
Clock app still crashing in BQ E4.5 (Krillin) running Ubuntu 16.04 (r85).

Unity8.log output https://paste.ubuntu.com/p/rgNntxGZkP/
Syslog output https://paste.ubuntu.com/p/SRrSNnd7gZ/

>May 27 11:53:56 ubuntu-phablet kernel: [46053.514298]init: ubuntu-location-provider-geoclue2 main process (28558) killed by SEGV signal

**Comment by dpniel** [comment] 2018-05-27 10:54
@zubozrout that doesn't look like the clock-app log. looks more like the log for the open-store app?

**Comment by dark-eye** [comment] 2018-05-27 12:47
thus is probably has something to do with the abi binding as ut seems to wirk without fail when theres no AlarmModel reference in the code a good compile configuration should fix it (unless it a problem with the alarmmodel it self) but ut will take me some time to get to ut as ill need to reflash my phone ( 16.04 has too much issues for a real daily driver use)

**Comment by zubozrout** [comment] 2018-05-27 13:17
@dpniel Oh, you are right, sorry about that. I've updated my original message to contain the correct log.

**Comment by jonnius** [comment] 2018-06-09 08:40
Thanks for the hint!

**Comment by nfsprodriver** [comment] 2018-08-14 17:05
fixed

**Closed by nfsprodriver** 2018-08-14 17:05 UTC

**Comment by jonnius** [comment] 2018-08-15 05:37
thanks!
